apiVersion: v1
kind: Pod
metadata:
  name: multi-busybox
spec:
  containers:
  - name: busybox
    image: busybox        
    command: ['sh', '-c', 'echo busybox1 is Running ; sleep 60000']
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80